FROM janlo/davical:latest
 ENV DAVICAL_SERVER_NAME    localhost
 ENV DAVICAL_DB_NAME        davical
 ENV DAVICAL_DB_USER        davical_app
 ENV DAVICAL_DB_PASS        davical
 ENV DAVICAL_DB_ADMIN       davical_dba
 ENV DAVICAL_DB_ADMIN_PASS  davical

